### ISSUE TITLE
setTimeout only runs once

### ISSUE THREAD

**Issue by RailtonMatthew** [fractaltech/react-native-timer#3]
When I run the code below I get "Ping" showing only twice in the console.  Why does it not run continually?

Thanks, Railton.

const timer = require('react-native-timer');

componentDidMount() {
    this.pcTimer();
}

pcTimer = () => {
    console.log("Ping");
    timer.setTimeout(this,'pcTimer',this.pcTimer,2000);
 }

**Comment by kapv89** [comment]
You see `"Ping"` only twice because that's how it works.

The first `"Ping"` comes from `this.pcTimer();`
The second `"Ping"` comes from `timer.setTimeout(this, 'pcTimer', this.pcTimer, 2000);`

As soon as the second ping happens, the timer `'pcTimer` is cleared. This causes the `setTimeout` to stop.

If you need continuous `ping`s, use `timer.setInterval`

```js
// timers maintained in the Map timer.intervals
timer.setInterval(name, fn, interval);
timer.clearInterval(name);
```

Let me know if this solves your problem. Thanks.

**Comment by RailtonMatthew** [comment]
Hi, thanks for the reply.  The function is calling itself so the timer is called again on each iteration.  If I change timer.setTimeout to setTimout then it pings continuously.

**Comment by kapv89** [comment]
I think your problem is solved. I am closing the issue. If you need anything else, just reopen the issue.
